import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        display: ["Cairo", "IBM Plex Sans Arabic", "sans-serif"],
        body:    ["Cairo", "IBM Plex Sans Arabic", "sans-serif"],
        sans:    ["Cairo", "IBM Plex Sans Arabic", "sans-serif"],
      },
      colors: {
        border:      "hsl(var(--border))",
        input:       "hsl(var(--input))",
        ring:        "hsl(var(--ring))",
        background:  "hsl(var(--background))",
        foreground:  "hsl(var(--foreground))",
        primary: {
          DEFAULT:   "hsl(var(--primary))",
          foreground:"hsl(var(--primary-foreground))",
          glow:      "hsl(var(--primary-glow))",
          subtle:    "hsl(var(--primary-subtle))",
          muted:     "hsl(var(--primary-muted))",
        },
        secondary:   { DEFAULT: "hsl(var(--secondary))",   foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted:       { DEFAULT: "hsl(var(--muted))",       foreground: "hsl(var(--muted-foreground))" },
        accent:      { DEFAULT: "hsl(var(--accent))",      foreground: "hsl(var(--accent-foreground))" },
        success:     { DEFAULT: "hsl(var(--success))",     foreground: "hsl(var(--success-foreground))" },
        popover:     { DEFAULT: "hsl(var(--popover))",     foreground: "hsl(var(--popover-foreground))" },
        card:        { DEFAULT: "hsl(var(--card))",        foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT:              "hsl(var(--sidebar-background))",
          foreground:           "hsl(var(--sidebar-foreground))",
          primary:              "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent:               "hsl(var(--sidebar-accent))",
          "accent-foreground":  "hsl(var(--sidebar-accent-foreground))",
          border:               "hsl(var(--sidebar-border))",
          ring:                 "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        "3xs": "0.25rem",
        "2xs": "0.375rem",
        xs:    "0.5rem",
        sm:    "0.75rem",
        md:    "1rem",
        lg:    "var(--radius)",
        xl:    "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        "4xl": "3rem",
        full:  "9999px",
      },
      boxShadow: {
        xs:       "var(--shadow-xs)",
        sm:       "var(--shadow-sm)",
        card:     "var(--shadow-card)",
        elevated: "var(--shadow-elevated)",
        glow:     "var(--shadow-glow)",
        inset:    "var(--shadow-inset)",
      },
      backgroundImage: {
        "gradient-brand":       "var(--gradient-brand)",
        "gradient-brand-soft":  "var(--gradient-brand-soft)",
        "gradient-hero":        "var(--gradient-hero)",
        "gradient-card":        "var(--gradient-card)",
      },
      keyframes: {
        "accordion-down":  { from: { height: "0" },                           to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":    { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in":         { from: { opacity: "0", transform: "translateY(10px)" },  to: { opacity: "1", transform: "translateY(0)" } },
        "fade-up":         { from: { opacity: "0", transform: "translateY(20px)" },  to: { opacity: "1", transform: "translateY(0)" } },
        "slide-in-right":  { from: { opacity: "0", transform: "translateX(24px)" },  to: { opacity: "1", transform: "translateX(0)" } },
        "scale-in":        { from: { opacity: "0", transform: "scale(0.92)" },        to: { opacity: "1", transform: "scale(1)" } },
        "bounce-in":       { "0%": { transform: "scale(0.8)", opacity: "0" }, "60%": { transform: "scale(1.05)" }, "100%": { transform: "scale(1)", opacity: "1" } },
        "neon-pulse":      { "0%, 100%": { boxShadow: "0 0 6px hsl(283 62% 60% / 0.60)" }, "50%": { boxShadow: "0 0 20px hsl(283 62% 60% / 1.0), 0 0 40px hsl(310 68% 68% / 0.50)" } },
        "shimmer":         { from: { backgroundPosition: "200% 0" }, to: { backgroundPosition: "-200% 0" } },
        "float":           { "0%, 100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-6px)" } },
      },
      animation: {
        "accordion-down":  "accordion-down 0.2s ease-out",
        "accordion-up":    "accordion-up 0.2s ease-out",
        "fade-in":         "fade-in 0.30s ease-out",
        "fade-up":         "fade-up 0.40s ease-out",
        "slide-in-right":  "slide-in-right 0.30s ease-out",
        "scale-in":        "scale-in 0.25s ease-out",
        "bounce-in":       "bounce-in 0.35s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "neon-pulse":      "neon-pulse 2.5s ease-in-out infinite",
        "shimmer":         "shimmer 1.8s linear infinite",
        "float":           "float 3s ease-in-out infinite",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
